### ISSUE TITLE
BadPageException: Could not parse player config json

### ISSUE THREAD

**Issue by ronanPoinsignon** [sealedtx/java-youtube-downloader#47] opened 2020-08-24 12:23 UTC
Hello,

link of the video : https://www.youtube.com/watch?v=QUvVdTlA23w

When i try to parse the video, i have this error :
com.github.kiulian.downloader.YoutubeException$BadPageException: Could not parse player config json
	at com.github.kiulian.downloader.parser.DefaultParser.getPlayerConfig(DefaultParser.java:72)
	at com.github.kiulian.downloader.YoutubeDownloader.getVideo(YoutubeDownloader.java:65)

I don't know if there are others links which give this error.

**Comment by sealedtx** [comment] 2020-08-24 12:56
@ronanPoinsignon Hi, just tested your videoId and it works fine. Could you please test any other videoId? Is error present only for this one or for any video? I would appriciate if you can clone source code and debug the problem, because I can't reproduce this error. You may print stacktrace and `ytPlayerConfig` string after line 76 and attach it to this issue: https://github.com/sealedtx/java-youtube-downloader/blob/cca2129661065a05808cb459fd7909d164c6acea/src/main/java/com/github/kiulian/downloader/parser/DefaultParser.java#L73-L78 
Thank you.

**Comment by ronanPoinsignon** [comment] 2020-08-24 13:05
Well i have restarted my program and it works fine too.
I'm a bit confused. I have tested 3 or 4 times with others videos and it was ok for all but my link.
I come back to you if i get more information.

**Comment by Wittano** [comment] 2020-08-24 13:30
In debug mode I found, that sometimes ytPlayerConfig doesn't end with '}' character

**Comment by sealedtx** [comment] 2020-08-24 13:42
@Wittano Could you please save whole html and ytPlayerConfig in txt files and attach them?

**Comment by Wittano** [comment] 2020-08-24 13:50
@sealedtx Ok
[html.txt](https://github.com/sealedtx/java-youtube-downloader/files/5118219/html.txt)
[ytPlayerConfig.txt](https://github.com/sealedtx/java-youtube-downloader/files/5118220/ytPlayerConfig.txt)

**Comment by sealedtx** [comment] 2020-08-24 15:11
@Wittano Thank you! Found solution:
Need to change regex for ytPlayerConfig search from `Pattern.compile(";ytplayer\\.config = (\\{.*?\\})\\;")` to `Pattern.compile(";ytplayer\\.config = (\\{.*?\\})\\;ytplayer")`, because on some pages it founds wrong closing "};" which causes exception. 
@ronanPoinsignon I will commit and release new version soon.

**Comment by sealedtx** [comment] 2020-08-25 08:25
Released 2.2.5

**Closed by sealedtx** 2020-08-25 08:25 UTC
